package org.uninpahu.Vistas.JPanels;

import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.uninpahu.ConfigPlayer.Reproductor;
import org.uninpahu.Controlers.ControlerSong;
import org.uninpahu.Modelo.Song;
import org.uninpahu.Vistas.JFrames.JFInformation;

public class JPPlaylist extends javax.swing.JPanel {

    DefaultTableModel dtm = new DefaultTableModel();
    ControlerSong controlerSong = new ControlerSong();
    Reproductor reproductor = new Reproductor();
    String selectedSong = null;

    public JPPlaylist() {
        initComponents();
        String[] tittle = new String[]{"Title", "Album", "Duration", "Gender"};
        dtm.setColumnIdentifiers(tittle);
        jTablePlaylist.setModel(dtm);
        addDataTableSongs();
    }

    private void addDataTableSongs() {
        Optional<List<Song>> songslist = controlerSong.listSong();
        songslist.ifPresent(songs -> {
            songs.forEach(songIterator -> dtm.addRow(new Object[]{
                songIterator.getNameSong(),
                songIterator.getIdAlbum().getNameAlbum(),
                songIterator.getDuration(),
                songIterator.getIdGender().getNameGender()
            }));
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlaylist = new javax.swing.JTable();
        jBPlaySong = new javax.swing.JButton();
        jBAddSong = new javax.swing.JButton();
        jBComment = new javax.swing.JButton();
        jBPlaySong2 = new javax.swing.JButton();
        jTogglePause = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(500, 411));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 411));

        jTablePlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Album", "Timen", "Actions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePlaylist);

        jBPlaySong.setIcon(new javax.swing.ImageIcon("/home/pipejfdv/Desktop/programs/SpotifyDesktop/src/main/java/org/uninpahu/Vistas/Images/botondeplay.png")); // NOI18N
        jBPlaySong.setText("  Play");
        jBPlaySong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlaySongActionPerformed(evt);
            }
        });

        jBAddSong.setIcon(new javax.swing.ImageIcon("/home/pipejfdv/Desktop/programs/SpotifyDesktop/src/main/java/org/uninpahu/Vistas/Images/anadir.png")); // NOI18N
        jBAddSong.setText("  Add Song to favorite");
        jBAddSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddSongActionPerformed(evt);
            }
        });

        jBComment.setIcon(new javax.swing.ImageIcon("/home/pipejfdv/Desktop/programs/SpotifyDesktop/src/main/java/org/uninpahu/Vistas/Images/comment.png")); // NOI18N
        jBComment.setText("  Comment");

        jBPlaySong2.setIcon(new javax.swing.ImageIcon("/home/pipejfdv/Desktop/programs/SpotifyDesktop/src/main/java/org/uninpahu/Vistas/Images/stop-button.png")); // NOI18N
        jBPlaySong2.setText("  Stop");
        jBPlaySong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlaySong2ActionPerformed(evt);
            }
        });

        jTogglePause.setIcon(new javax.swing.ImageIcon("/home/pipejfdv/Desktop/programs/SpotifyDesktop/src/main/java/org/uninpahu/Vistas/Images/pause-button.png")); // NOI18N
        jTogglePause.setText("  Pause");
        jTogglePause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTogglePauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jBComment)
                .addGap(48, 48, 48)
                .addComponent(jBAddSong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jBPlaySong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTogglePause)
                .addGap(65, 65, 65)
                .addComponent(jBPlaySong2)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBPlaySong)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBPlaySong2)
                        .addComponent(jTogglePause)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAddSong)
                    .addComponent(jBComment))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBPlaySongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlaySongActionPerformed
        int row = jTablePlaylist.getSelectedRow();
        if (row >= 0) {
            selectedSong = jTablePlaylist.getValueAt(row, 0).toString();
            Song song = controlerSong.searchSong(null, selectedSong);
            reproductor.play(song.getPathFile());
        }
    }//GEN-LAST:event_jBPlaySongActionPerformed

    private void jBPlaySong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlaySong2ActionPerformed
        reproductor.stopSong();
    }//GEN-LAST:event_jBPlaySong2ActionPerformed

    private void jTogglePauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTogglePauseActionPerformed
        if (jTogglePause.isSelected()) {
            reproductor.pauseSong();
        } else {
            reproductor.resumeSong();
        }
    }//GEN-LAST:event_jTogglePauseActionPerformed

    private void jBAddSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddSongActionPerformed

        int row = jTablePlaylist.getSelectedRow();
        if (row >= 0) {
            JFInformation information = new JFInformation();
            information.setSongSelect(selectedSong = jTablePlaylist.getValueAt(row, 0).toString());
            information.setVisible(true);
            information.setLocationRelativeTo(null);
            information.setResizable(false);
        } else {
            JOptionPane.showMessageDialog(null, "Select a song first");
        }
    }//GEN-LAST:event_jBAddSongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddSong;
    private javax.swing.JButton jBComment;
    private javax.swing.JButton jBPlaySong;
    private javax.swing.JButton jBPlaySong2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlaylist;
    private javax.swing.JToggleButton jTogglePause;
    // End of variables declaration//GEN-END:variables
}
